name: Tests Pipeline

on:
  push:
    branches: [ master, feat/gh-actions-docker-build ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      APP_NAME: wallet
    steps:
      - if: github.ref != 'refs/heads/develop'
        uses: actions/checkout@v2
        with:
          ref: develop
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - if: github.ref != 'refs/heads/develop'
        run: git branch develop origin/develop
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run lint
      - run: npm test
